#!/usr/bin/env oo-ruby

require "/var/www/openshift/broker/config/environment"
# Disable analytics for admin scripts
Rails.configuration.analytics[:enabled] = false

Application.all.each do |app|
  app.run_connection_hooks
end
