#!/bin/bash

set -xe

conf=/etc/openshift/node.conf
command cp -f $conf{,.ugsave.`date +%Y-%m-%d-%H:%M:%S`}

# Add the following settings that are new in RHOSE 2.1:
#
#
#  * Add the OPENSHIFT_FRONTEND_HTTP_PLUGINS setting (see commits
#    ac95820e77f5b6d27acd474a9a08f742849e51de and
#    8ab901e7dba8c50157bbfd59a2dd55b51d17a57a).
cat <<EOF >> $conf

REPORT_BUILD_ANALYTICS=false
EOF
