#!/bin/bash -x

tmpfile=/tmp/repolist-$$-`date +%N`
yum repolist > $tmpfile 2> /dev/null

declare -a added_repos

for channel in infra node jbosseap rhc; do
  if grep -q rhel-server-ose-${channel}-6-rpms $tmpfile; then
    # all channels need to move to version 2
    yum-config-manager --disable rhel-server-ose-${channel}-6-rpms
    yum-config-manager --enable rhel-server-ose-1.2-${channel}-6-rpms
    added_repos+=("rhel-server-ose-1.2-${channel}-6-rpms")
  fi
done

if grep -q jb-ews-1-for-rhel-6-server-rpms $tmpfile; then
    # make sure we point to the jboss ews 2 repo
    yum-config-manager --disable jb-ews-1-for-rhel-6-server-rpms
    yum-config-manager --enable jb-ews-2-for-rhel-6-server-rpms
    added_repos+=("jb-ews-2-for-rhel-6-server-rpms")
fi

yum clean all
yum repolist > $tmpfile 2> /dev/null

for repo in "${added_repos[@]}"; do
  if ! grep -q $repo $tmpfile; then
    failure="$repo $failure"
  fi
done

rm -f $tmpfile

if [ -n "$failure" ] ; then
  echo "ERROR - Could not enable the following repositories:"
  echo "$failure"
  exit 1
fi

exit 0
