#!/bin/bash

set -e

if grep "^uuid" /var/lib/openshift/.settings/district.info 2>&1 > /dev/null
then
  echo "SUCCESS: Node exists in district"
else
  echo "FAILURE: This Node is not in any district."
  echo "FAILURE: Any Gears on these Nodes must first be migrated to districted Nodes."
  echo "FAILURE: Please refer to the OpenShift Enterprise Administration Guide for more details:"
  echo "https://access.redhat.com/site/documentation/en-US/OpenShift_Enterprise/2/html/Administration_Guide/chap-Resource_Management.html"
  exit 1
fi
