#!/bin/bash -x

# clear the cache which likely has root-owned things in it
oo-admin-broker-cache --clear

# make sure apache owns the files it logs to
chown -R apache:root /var/log/openshift/broker
chown apache:root /var/log/mcollective-client.log

for svc in openshift-broker
do
	service $svc start
done

service httpd graceful

exit 0
