#!/usr/bin/env oo-ruby

puts "Loading the broker rails environment."
require "/var/www/openshift/broker/config/environment"
Rails.configuration.analytics[:enabled] = false

puts "Retrieving list of expected nodes."
nodes_in_districts = District.all.distinct('server_identities.name')
nodes_with_gears = Application.all.distinct('group_instances.gears.server_identity')

problem_nodes = nodes_with_gears - nodes_in_districts
if problem_nodes.empty?
  puts "SUCCESS: No undistricted OpenShift Nodes with Gears found."
  exit 0
else
  puts "FAILURE: The following OpenShift Nodes have Gears and are not in any District:"
  problem_nodes.each {|n| puts n}
  puts "FAILURE: Please refer to the OpenShift Enterprise Administration Guide for more details on how to migrate Gears on these Nodes: "
  puts "https://access.redhat.com/site/documentation/en-US/OpenShift_Enterprise/2/html/Administration_Guide/chap-Resource_Management.html"
  exit 1
end
