#!/bin/bash

set -xe

# Backup remote user conf.
conf=`ls /var/www/openshift/broker/httpd/conf.d/openshift-origin-auth*.conf`
command cp -f "$conf"{,.ugsave.`date +%Y-%m-%d-%H:%M:%S`}

sed -i 's/BrowserMatchNoCase.*passthrough/SetEnvIf broker_auth_key "^[A-Za-z0-9+\/=]+$" passthrough=1/' $conf
sed -i 's/local_traffic=1/passthrough=1/' $conf
