#!/bin/bash -x

# need these workarounds when broker and node are installed together

# mod_rewrite acts before proxypass so need to incorporate the previous proxy rules as rewriterules.
  cat <<EOF >> /var/lib/openshift/.httpd.d/nodes.txt || exit 1
__default__ REDIRECT:/console
__default__/console TOHTTPS:127.0.0.1:8118/console
__default__/broker TOHTTPS:127.0.0.1:8080/broker
EOF

  httxt2dbm -f DB -i /etc/httpd/conf.d/openshift/nodes.txt -o /etc/httpd/conf.d/openshift/nodes.db || exit 1
  chown root:apache /etc/httpd/conf.d/openshift/nodes.txt /etc/httpd/conf.d/openshift/nodes.db || exit 1
  chmod 750 /etc/httpd/conf.d/openshift/nodes.txt /etc/httpd/conf.d/openshift/nodes.db || exit 1

exit 0
