#!/bin/bash -x


# check that the dns-bind RPM is in place, or skip this
rpm -q rubygem-openshift-origin-dns-bind || exit 0
[ -f /etc/openshift/plugins.d/openshift-origin-dns-bind.conf ] || exit 0

# assumption: you were using the dns-bind plugin rather than something custom
yum remove -y rubygem-openshift-origin-dns-bind || exit 1
yum install -y rubygem-openshift-origin-dns-nsupdate || exit 1
mv /etc/openshift/plugins.d/openshift-origin-dns-{bind,nsupdate}.conf || exit 1

exit 0
