#!/bin/bash

set -xe

get_package_version() {
  pkg_name=$1
  pkg_ver_ref=$2
  pkg_rel_ref=$3

  if ! pkg_ver_rel=( $(rpm -q ${pkg_name} --qf '%{VERSION} %{RELEASE}\n') ); then
    return 1
  fi
  eval $pkg_ver_ref=${pkg_ver_rel[0]}
  eval $pkg_rel_ref=${pkg_ver_rel[1]}
  return 0
}

is_scl_1_1_package() {
  pkg_name=$1
  pkg_ver=$2
  pkg_rel=$3

  declare -A packages
  packages[scl-utils]="20120927 11.el6_5"
  packages[ruby193-ruby]="1.9.3.484 49.el6"
  packages[v8314-v8]="3.14.5.10 3.6.el6"

  [ ${packages[$pkg_name]+_} ] || return 1
  scl_pkg_ver_rel=( ${packages[$pkg_name]} )
  scl_pkg_ver=${scl_pkg_ver_rel[0]}
  scl_pkg_rel=${scl_pkg_ver_rel[1]}
  if [ $(python -c "import rpmUtils.miscutils; print(rpmUtils.miscutils.compareEVR(('${pkg_name}', '${pkg_ver}', '${pkg_rel}'), ('${pkg_name}', '${scl_pkg_ver}', '${scl_pkg_rel}')) >= 0)") == 'True' ]; then
    return 0
  else
    return 1
  fi
}

is_scl_1_1() {
  pkg_ver=""
  pkg_rel=""
  for pkg in scl-utils ruby193-ruby v8314-v8; do
    if ! get_package_version $pkg pkg_ver pkg_rel; then
      return 1
    else
      if ! is_scl_1_1_package $pkg $pkg_ver $pkg_rel; then
        return 1
      fi
    fi
  done
  return 0
}

SCLS="ruby193"
if is_scl_1_1; then
  SCLS+=" v8314"
fi

# https://engineering.redhat.com/trac/Libra/wiki/Releases/2.0.36#Comment6
cd /var/www/openshift/broker
scl enable $SCLS "bundle exec rails runner 'Authorization.create_indexes'"
