#!/bin/bash -x

yum/01-both-internal-yum-repos || exit
yum/02-both-yum-plugin-priorities || exit
any/03-broker-shutdown-services || exit
any/04-both-yum-update || exit
any/05a-broker-update-dns-plugin || exit
any/05b-broker-fix-mongo-gems || exit
any/05c-broker-adjust-rails || exit
any/06-broker-mongodb-migration || exit
any/07-both-fix-contexts || exit
any/08-broker-fix-conf-broker || exit
any/08-broker-fix-conf-mcollective || exit
any/08-broker-fix-conf-console || exit
any/08-broker-fix-conf-remote-user || exit
any/09-node-web-proxy || exit
echo "Broker upgrade complete! Reboot when node upgrade is complete!"
