#!/bin/bash -x

yum/01-both-internal-yum-repos || exit
yum/02-both-yum-plugin-priorities || exit
any/03-broker-shutdown-services || exit
any/03-node-shutdown-services || exit
any/04-both-yum-update || exit
any/05-node-add-v2-cartridges || exit
any/05a-broker-update-dns-plugin
any/05b-broker-fix-mongo-gems
any/05c-broker-adjust-rails
any/06-broker-mongodb-migration || exit
any/07-both-fix-contexts || exit
any/08-broker-fix-conf-broker || exit
any/08-broker-fix-conf-mcollective || exit
any/08-broker-fix-conf-console || exit
any/08-broker-fix-conf-remote-user || exit
any/08-node-fix-conf-node || exit
any/08-node-fix-conf-mcollective || exit
any/09-node-web-proxy || exit
any/10-combo-fixes || exit
any/11-node-cgconfig || exit
any/12-node-migrate-gears || exit
echo "Broker+node upgrade complete! Time to reboot!"

