#!/bin/bash -x

# assumptions: everything is installed on the broker
# although actually the services that aren't installed will simply fail to stop and complain

for svc in crond httpd mcollective openshift-port-proxy openshift-gears
do
	service $svc stop
done
exit 0
