#!/bin/bash -x

# assumption: you want to use all the v2 cartridges
yum install -y --skip-broken *cartridge* || exit 1

# we could run the script but don't really want to restart the broker at this point
#oo-cart-version -c v2 || exit 1

# just place the marker file
touch /var/lib/openshift/.settings/v2_cartridge_format

exit 0
