#!/bin/bash -x

# /etc/cgconfig.conf now is copied from /opt/rh/ruby193/root/usr/share/gems/doc/openshift-origin-node-*/cgconfig.conf and includes some changes from the previously released version

mv /etc/cgconfig.conf{,.rpmsave}  # in case you customized it somehow, it's saved and will show up in an audit
cp -vf /opt/rh/ruby193/root/usr/share/gems/doc/openshift-origin-node-*/cgconfig.conf /etc/cgconfig.conf || exit 1
restorecon -rv /etc/cgconfig.conf || exit 1

exit 0
