#!/bin/bash

set -xe

# These files were backed up in the backup-conf step, qv.
#
# Note that it is critical that this step be performed before
# upgrades/2/conf_with_node/10-combo-fixes (which operate on nodes.db and
# nodes.txt) is run.
command cp -f /etc/openshift/upgrade/2/000001_openshift_origin_node_servername.conf /etc/httpd/conf.d/
command cp -f /etc/openshift/upgrade/2/nodes.db    /var/lib/openshift/.httpd.d/
command cp -f /etc/openshift/upgrade/2/nodes.txt   /var/lib/openshift/.httpd.d/
command cp -f /etc/openshift/upgrade/2/geardb.json /var/lib/openshift/.httpd.d/
command cp -f /etc/openshift/upgrade/2/routes.json /var/lib/openshift/.httpd.d/
