#!/bin/bash

set -xe

conf='/etc/sysctl.conf'
command cp -f "$conf"{,.ugsave.`date +%Y-%m-%d-%H:%M:%S`}

# openshift-iptables-port-proxy requires several additional NAT-related
# sysctl settings to be changed that the old openshift-port-proxy did
# not need.
if ! grep -q 'net\.ipv4\.ip_forward\s*=\s*1\>' "$conf"
then
  cat <<EOF >> $conf

# Enable forwarding for the OpenShift port proxy.
net.ipv4.ip_forward = 1
EOF
fi

if ! grep -q 'net\.ipv4\.conf\.all\.route_localnet=\s*1\>' "$conf"
then
  cat <<EOF >> $conf

# Allow the OpenShift port proxy to route using loopback addresses.
net.ipv4.conf.all.route_localnet = 1
EOF
fi

chkconfig openshift-iptables-port-proxy on

# openshift-iptables-port-proxy hooks into the iptables configuration by
# adding a new table and having the INPUT chain jump to this new table.
if ! iptables -L rhc-app-comm > /dev/null 2>&1
then
  iptables -N rhc-app-comm
  iptables -I INPUT 4 -j rhc-app-comm
fi

# Make sure that the above modifications to iptables persist.
service iptables save
