#!/bin/bash -x

cp /etc/mcollective/client.cfg{,.ugsave.`date +%Y-%m-%d-%H:%M:%S`} || exit 1

# use the ruby193 SCL-ized mcollective directory
# use direct addressing
# move logfile
# bump loglevel to warn
sed -i '/^libdir/ c\
libdir = /opt/rh/ruby193/root/usr/libexec/mcollective
/^direct_addressing/d
/^logfile/ c\
logfile = /var/log/openshift/broker/mcollective-client.log
/^loglevel/ c\
loglevel = warn
/^collectives/ a\
direct_addressing = 1' /etc/mcollective/client.cfg || exit 1

touch /var/log/openshift/broker/mcollective-client.log
chown apache:root /var/log/openshift/broker/mcollective-client.log

exit 0
