#!/bin/bash

# expects to be called from Makefile at ..

cp -f openshift.ks $1

# set the default base url to our internal puddles
sed -i -e '
/^repos_base_default=.*/ a\
repos_base_default=http://buildvm-devops.usersys.redhat.com/puddle/build/OpenShiftEnterprise/Beta/latest
' $1
sed -i -e 's/^gpgcheck=0/gpgcheck=0\nsslverify=false/g' $1

# update the console msg with useful stuff
sed -i -e '
/^echo_installation_intentions$/ a\
configure_console_msg
' $1

# allow installation of carts to proceed as possible even if packaging is borked
sed -i -e 's/#\(carts.*--skip-broken\)/\1/' $1

# configure RHEL to use internal repo
ruby -p -i -e 'if $_ =~ /# configure RHEL subscription or repos here/; $_ = "  #" + $_[2..-1] + "  cat <<EOF > /etc/yum.repos.d/rhel.repo\n" + File.open("internal/rhel.repo").read + "\nEOF\n" end' $1

