#!/bin/bash

set -xe

# Assumptions: Console is installed on the broker.

# Clear the cache.
oo-admin-broker-cache --clear --console

for svc in openshift-broker openshift-console
do
	service "$svc" start
done

service httpd graceful
