#!/bin/bash

set -xe

beta='--repo-config /etc/yum-validator/beta2.ini'
#beta=

# It's OK for oo-admin-yum-validator to return a bunch of errors; it
# does that even if it fixes things.
/usr/bin/oo-admin-yum-validator --oo-version 2.0 ${beta} --fix-all || :

# Now we run oo-admin-yum-validator again though to make sure that
# there are no errors remaining, and this time we heed the exit code.
/usr/bin/oo-admin-yum-validator --oo-version 2.0 ${beta} --report-all
